// Generated by opengeodeweb-microservice-generate, do not edit.
import type json from "./opengeodeweb_viewer_schemas.json";

export interface GenericRegisterParams {
    id:   string;
    name: string;
}

export interface GenericRegisterResponse {
}

export interface GenericDeregisterParams {
    id: string;
}

export interface GenericDeregisterResponse {
}

export interface MeshCellsAttributeCellAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshCellsAttributeCellAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshCellsAttributeCellAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshCellsAttributeCellAttributeResponse {
}

export interface MeshCellsAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshCellsAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshCellsAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshCellsAttributeVertexAttributeResponse {
}

export interface MeshCellsVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshCellsVisibilityResponse {
}

export interface MeshCellsColorParams {
    color: MeshCellsColorParamsColor;
    id:    string;
}

export interface MeshCellsColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshCellsColorResponse {
}

export interface MeshEdgesAttributeEdgeAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshEdgesAttributeEdgeAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshEdgesAttributeEdgeAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshEdgesAttributeEdgeAttributeResponse {
}

export interface MeshEdgesAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshEdgesAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshEdgesAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshEdgesAttributeVertexAttributeResponse {
}

export interface MeshEdgesWidthParams {
    id:    string;
    width: number;
}

export interface MeshEdgesWidthResponse {
}

export interface MeshEdgesVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshEdgesVisibilityResponse {
}

export interface MeshEdgesColorParams {
    color: MeshEdgesColorParamsColor;
    id:    string;
}

export interface MeshEdgesColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshEdgesColorResponse {
}

export interface MeshPointsAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPointsAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPointsAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPointsAttributeVertexAttributeResponse {
}

export interface MeshPointsVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshPointsVisibilityResponse {
    id:         string;
    visibility: boolean;
}

export interface MeshPointsSizeParams {
    id:   string;
    size: number;
}

export interface MeshPointsSizeResponse {
}

export interface MeshPointsColorParams {
    color: MeshPointsColorParamsColor;
    id:    string;
}

export interface MeshPointsColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPointsColorResponse {
}

export interface MeshPolygonsAttributePolygonAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPolygonsAttributePolygonAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPolygonsAttributePolygonAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolygonsAttributePolygonAttributeResponse {
}

export interface MeshPolygonsAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPolygonsAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPolygonsAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolygonsAttributeVertexAttributeResponse {
}

export interface MeshPolygonsVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshPolygonsVisibilityResponse {
}

export interface MeshPolygonsColorParams {
    color: MeshPolygonsColorParamsColor;
    id:    string;
}

export interface MeshPolygonsColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolygonsColorResponse {
}

export interface MeshPolyhedraAttributePolyhedronAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPolyhedraAttributePolyhedronAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPolyhedraAttributePolyhedronAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolyhedraAttributePolyhedronAttributeResponse {
}

export interface MeshPolyhedraAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPolyhedraAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPolyhedraAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolyhedraAttributeVertexAttributeResponse {
}

export interface MeshPolyhedraVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshPolyhedraVisibilityResponse {
}

export interface MeshPolyhedraColorParams {
    color: MeshPolyhedraColorParamsColor;
    id:    string;
}

export interface MeshPolyhedraColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolyhedraColorResponse {
}

export interface MeshVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshVisibilityResponse {
}

export interface MeshRegisterParams {
    id:   string;
    name: string;
}

export interface MeshRegisterResponse {
}

export interface MeshHighlightParams {
    id:         string;
    visibility: boolean;
}

export interface MeshHighlightResponse {
}

export interface MeshDeregisterParams {
    id: string;
}

export interface MeshDeregisterResponse {
}

export interface MeshColorParams {
    color: MeshColorParamsColor;
    id:    string;
}

export interface MeshColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshColorResponse {
}

export interface MeshApplyTexturesParams {
    id:       string;
    textures: MeshApplyTexturesParamsTexture[];
}

export interface MeshApplyTexturesParamsTexture {
    id:           string;
    texture_name: string;
}

export interface MeshApplyTexturesResponse {
}

export interface ModelBlocksAttributePolyhedronAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelBlocksAttributePolyhedronAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelBlocksAttributePolyhedronAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelBlocksAttributePolyhedronAttributeResponse {
}

export interface ModelBlocksAttributeVertexAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelBlocksAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelBlocksAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelBlocksAttributeVertexAttributeResponse {
}

export interface ModelBlocksVisibilityParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelBlocksVisibilityResponse {
}

export interface ModelBlocksColorParams {
    block_ids:      number[];
    collection_id?: string;
    color?:         ModelBlocksColorParamsColor;
    color_mode:     ColorMode;
    id:             string;
}

export interface ModelBlocksColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export type ColorMode = "constant" | "random";

export interface ModelBlocksColorResponse {
    colors: ModelBlocksColorResponseColor[];
}

export interface ModelBlocksColorResponseColor {
    color:     PurpleColorRGBA;
    geode_id:  string;
    viewer_id: number;
}

export interface PurpleColorRGBA {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelCornersAttributeVertexAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelCornersAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelCornersAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelCornersAttributeVertexAttributeResponse {
}

export interface ModelCornersVisibilityParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelCornersVisibilityResponse {
}

export interface ModelCornersColorParams {
    block_ids:      number[];
    collection_id?: string;
    color?:         ModelCornersColorParamsColor;
    color_mode:     ColorMode;
    id:             string;
}

export interface ModelCornersColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelCornersColorResponse {
    colors: ModelCornersColorResponseColor[];
}

export interface ModelCornersColorResponseColor {
    color:     FluffyColorRGBA;
    geode_id:  string;
    viewer_id: number;
}

export interface FluffyColorRGBA {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelEdgesVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface ModelEdgesVisibilityResponse {
}

export interface ModelLinesAttributeEdgeAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelLinesAttributeEdgeAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelLinesAttributeEdgeAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelLinesAttributeEdgeAttributeResponse {
}

export interface ModelLinesAttributeVertexAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelLinesAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelLinesAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelLinesAttributeVertexAttributeResponse {
}

export interface ModelLinesVisibilityParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelLinesVisibilityResponse {
}

export interface ModelLinesColorParams {
    block_ids:      number[];
    collection_id?: string;
    color?:         ModelLinesColorParamsColor;
    color_mode:     ColorMode;
    id:             string;
}

export interface ModelLinesColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelLinesColorResponse {
    colors: ModelLinesColorResponseColor[];
}

export interface ModelLinesColorResponseColor {
    color:     TentacledColorRGBA;
    geode_id:  string;
    viewer_id: number;
}

export interface TentacledColorRGBA {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelPointsVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface ModelPointsVisibilityResponse {
}

export interface ModelPointsSizeParams {
    id:   string;
    size: number;
}

export interface ModelPointsSizeResponse {
}

export interface ModelVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface ModelVisibilityResponse {
}

export interface ModelRegisterParams {
    id:   string;
    name: string;
}

export interface ModelRegisterResponse {
}

export interface ModelHighlightParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelHighlightResponse {
}

export interface ModelGetBlocksBoundsParams {
    block_ids: number[];
    id:        string;
}

export interface ModelGetBlocksBoundsResponse {
    bounds: number[];
}

export interface ModelDeregisterParams {
    id: string;
}

export interface ModelDeregisterResponse {
}

export interface ModelSurfacesAttributePolygonAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelSurfacesAttributePolygonAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelSurfacesAttributePolygonAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelSurfacesAttributePolygonAttributeResponse {
}

export interface ModelSurfacesAttributeVertexAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelSurfacesAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelSurfacesAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelSurfacesAttributeVertexAttributeResponse {
}

export interface ModelSurfacesVisibilityParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelSurfacesVisibilityResponse {
}

export interface ModelSurfacesColorParams {
    block_ids:      number[];
    collection_id?: string;
    color?:         ModelSurfacesColorParamsColor;
    color_mode:     ColorMode;
    id:             string;
}

export interface ModelSurfacesColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelSurfacesColorResponse {
    colors: ModelSurfacesColorResponseColor[];
}

export interface ModelSurfacesColorResponseColor {
    color:     StickyColorRGBA;
    geode_id:  string;
    viewer_id: number;
}

export interface StickyColorRGBA {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelSurfacesApplyTexturesParams {
    id:       string;
    textures: ModelSurfacesApplyTexturesParamsTexture[];
}

export interface ModelSurfacesApplyTexturesParamsTexture {
    texture_file_name: string;
    texture_name:      string;
}

export interface ModelSurfacesApplyTexturesResponse {
}

export interface ReleaseDatabaseParams {
}

export interface ReleaseDatabaseResponse {
}

export interface KillParams {
}

export interface KillResponse {
}

export interface ImportProjectParams {
}

export interface ImportProjectResponse {
}

export interface ViewerUpdateDataParams {
    id: string;
}

export interface ViewerUpdateDataResponse {
}

export interface ViewerUpdateCameraParams {
    camera_options: CameraOptions;
    [property: string]: any;
}

export interface CameraOptions {
    clipping_range: number[];
    focal_point:    number[];
    position:       number[];
    view_angle:     number;
    view_up:        number[];
    [property: string]: any;
}

export interface ViewerUpdateCameraResponse {
}

export interface ViewerThresholdParams {
    attribute?: AttributeClass;
    ids:        string[];
}

export interface AttributeClass {
    item:     number;
    location: Location;
    maximum:  number;
    minimum:  number;
    name:     string;
}

export type Location = "point" | "cell";

export interface ViewerThresholdResponse {
}

export interface ViewerTakeScreenshotParams {
    filename:           string;
    include_background: boolean;
    output_extension:   OutputExtension;
}

export type OutputExtension = "png" | "jpg";

export interface ViewerTakeScreenshotResponse {
    blob: string;
}

export interface ViewerSliceParams {
    ids:    string[];
    slices: Slice[];
}

export interface Slice {
    axis:  number;
    index: number;
}

export interface ViewerSliceResponse {
    max_indices: number[];
}

export interface ViewerShrinkParams {
    ids:           string[];
    shrink_factor: number;
}

export interface ViewerShrinkResponse {
}

export interface ViewerSetZScalingParams {
    z_scale: number;
}

export interface ViewerSetZScalingResponse {
}

export interface ViewerSetBackgroundColorParams {
    color: ViewerSetBackgroundColorParamsColor;
}

export interface ViewerSetBackgroundColorParamsColor {
    b: number;
    g: number;
    r: number;
}

export interface ViewerSetBackgroundColorResponse {
}

export interface ViewerRulerParams {
    points: Array<number[]>;
}

export interface ViewerRulerResponse {
    distance: number;
    point1:   number[];
    point2?:  number[];
}

export interface ViewerResetVisualizationParams {
}

export interface ViewerResetVisualizationResponse {
}

export interface ViewerResetRulerParams {
}

export interface ViewerResetRulerResponse {
}

export interface ViewerResetCameraParams {
}

export interface ViewerResetCameraResponse {
}

export interface ViewerRenderParams {
}

export interface ViewerRenderResponse {
}

export interface ViewerPreviewPointsParams {
    closed?: boolean;
    points:  Point[];
    style:   Style;
}

export interface Point {
    x: number;
    y: number;
    z: number;
}

export type Style = "points" | "curve" | "surface";

export interface ViewerPreviewPointsResponse {
}

export interface ViewerPickedIDSParams {
    ids: string[];
    x:   number;
    y:   number;
}

export interface ViewerPickedIDSResponse {
    array_ids:  string[];
    viewer_id?: number;
}

export interface ViewerPickColormapParams {
    x: number;
    y: number;
    [property: string]: any;
}

export interface ViewerPickColormapResponse {
    data_id?: string;
}

export interface ViewerHighlightParams {
    field_type: PickedFieldType;
    ids:        string[];
    x:          number;
    y:          number;
}

export type PickedFieldType = "CELL" | "POINT";

export interface ViewerHighlightResponse {
    attributes?: { [key: string]: number[] | number };
    field_type?: PickedFieldType;
    geode_id?:   string;
    id?:         string;
    picked_id?:  number;
}

export interface ViewerGridScaleParams {
    visibility: boolean;
}

export interface ViewerGridScaleResponse {
}

export interface ViewerGetPointPositionParams {
    x: number;
    y: number;
}

export interface ViewerGetPointPositionResponse {
    x: number;
    y: number;
    z: number;
}

export interface ViewerClippingPlanesParams {
    ids:    string[];
    planes: Plane[];
}

export interface Plane {
    normal: number[];
    origin: number[];
}

export interface ViewerClippingPlanesResponse {
}

export interface ViewerAxesParams {
    visibility: boolean;
}

export interface ViewerAxesResponse {
}

export interface ErrorResponse {
    code:        number;
    description: string;
    name:        string;
}

// `__params` and `__response` only exist at type level, to infer request/response types from a schema.
// A type alias (not an interface) keeps the implicit index signature of the JSON type it is intersected with.
export type TypedSchema<Params, Response> = {
  readonly __params?: Params;
  readonly __response?: Response;
};

export interface Schemas {
  readonly opengeodeweb_viewer: {
    readonly generic: {
      readonly register: (typeof json)["opengeodeweb_viewer"]["generic"]["register"] & TypedSchema<GenericRegisterParams, GenericRegisterResponse>;
      readonly deregister: (typeof json)["opengeodeweb_viewer"]["generic"]["deregister"] & TypedSchema<GenericDeregisterParams, GenericDeregisterResponse>;
    };
    readonly mesh: {
      readonly cells: {
        readonly attribute: {
          readonly cell: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["cells"]["attribute"]["cell"]["attribute"] & TypedSchema<MeshCellsAttributeCellAttributeParams, MeshCellsAttributeCellAttributeResponse>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["cells"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshCellsAttributeVertexAttributeParams, MeshCellsAttributeVertexAttributeResponse>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["cells"]["visibility"] & TypedSchema<MeshCellsVisibilityParams, MeshCellsVisibilityResponse>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["cells"]["color"] & TypedSchema<MeshCellsColorParams, MeshCellsColorResponse>;
      };
      readonly edges: {
        readonly attribute: {
          readonly edge: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["attribute"]["edge"]["attribute"] & TypedSchema<MeshEdgesAttributeEdgeAttributeParams, MeshEdgesAttributeEdgeAttributeResponse>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshEdgesAttributeVertexAttributeParams, MeshEdgesAttributeVertexAttributeResponse>;
          };
        };
        readonly width: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["width"] & TypedSchema<MeshEdgesWidthParams, MeshEdgesWidthResponse>;
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["visibility"] & TypedSchema<MeshEdgesVisibilityParams, MeshEdgesVisibilityResponse>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["color"] & TypedSchema<MeshEdgesColorParams, MeshEdgesColorResponse>;
      };
      readonly points: {
        readonly attribute: {
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["points"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshPointsAttributeVertexAttributeParams, MeshPointsAttributeVertexAttributeResponse>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["points"]["visibility"] & TypedSchema<MeshPointsVisibilityParams, MeshPointsVisibilityResponse>;
        readonly size: (typeof json)["opengeodeweb_viewer"]["mesh"]["points"]["size"] & TypedSchema<MeshPointsSizeParams, MeshPointsSizeResponse>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["points"]["color"] & TypedSchema<MeshPointsColorParams, MeshPointsColorResponse>;
      };
      readonly polygons: {
        readonly attribute: {
          readonly polygon: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["polygons"]["attribute"]["polygon"]["attribute"] & TypedSchema<MeshPolygonsAttributePolygonAttributeParams, MeshPolygonsAttributePolygonAttributeResponse>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["polygons"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshPolygonsAttributeVertexAttributeParams, MeshPolygonsAttributeVertexAttributeResponse>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["polygons"]["visibility"] & TypedSchema<MeshPolygonsVisibilityParams, MeshPolygonsVisibilityResponse>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["polygons"]["color"] & TypedSchema<MeshPolygonsColorParams, MeshPolygonsColorResponse>;
      };
      readonly polyhedra: {
        readonly attribute: {
          readonly polyhedron: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["polyhedra"]["attribute"]["polyhedron"]["attribute"] & TypedSchema<MeshPolyhedraAttributePolyhedronAttributeParams, MeshPolyhedraAttributePolyhedronAttributeResponse>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["polyhedra"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshPolyhedraAttributeVertexAttributeParams, MeshPolyhedraAttributeVertexAttributeResponse>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["polyhedra"]["visibility"] & TypedSchema<MeshPolyhedraVisibilityParams, MeshPolyhedraVisibilityResponse>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["polyhedra"]["color"] & TypedSchema<MeshPolyhedraColorParams, MeshPolyhedraColorResponse>;
      };
      readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["visibility"] & TypedSchema<MeshVisibilityParams, MeshVisibilityResponse>;
      readonly register: (typeof json)["opengeodeweb_viewer"]["mesh"]["register"] & TypedSchema<MeshRegisterParams, MeshRegisterResponse>;
      readonly highlight: (typeof json)["opengeodeweb_viewer"]["mesh"]["highlight"] & TypedSchema<MeshHighlightParams, MeshHighlightResponse>;
      readonly deregister: (typeof json)["opengeodeweb_viewer"]["mesh"]["deregister"] & TypedSchema<MeshDeregisterParams, MeshDeregisterResponse>;
      readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["color"] & TypedSchema<MeshColorParams, MeshColorResponse>;
      readonly apply_textures: (typeof json)["opengeodeweb_viewer"]["mesh"]["apply_textures"] & TypedSchema<MeshApplyTexturesParams, MeshApplyTexturesResponse>;
    };
    readonly model: {
      readonly blocks: {
        readonly attribute: {
          readonly polyhedron: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["blocks"]["attribute"]["polyhedron"]["attribute"] & TypedSchema<ModelBlocksAttributePolyhedronAttributeParams, ModelBlocksAttributePolyhedronAttributeResponse>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["blocks"]["attribute"]["vertex"]["attribute"] & TypedSchema<ModelBlocksAttributeVertexAttributeParams, ModelBlocksAttributeVertexAttributeResponse>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["blocks"]["visibility"] & TypedSchema<ModelBlocksVisibilityParams, ModelBlocksVisibilityResponse>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["model"]["blocks"]["color"] & TypedSchema<ModelBlocksColorParams, ModelBlocksColorResponse>;
      };
      readonly corners: {
        readonly attribute: {
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["corners"]["attribute"]["vertex"]["attribute"] & TypedSchema<ModelCornersAttributeVertexAttributeParams, ModelCornersAttributeVertexAttributeResponse>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["corners"]["visibility"] & TypedSchema<ModelCornersVisibilityParams, ModelCornersVisibilityResponse>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["model"]["corners"]["color"] & TypedSchema<ModelCornersColorParams, ModelCornersColorResponse>;
      };
      readonly edges: {
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["edges"]["visibility"] & TypedSchema<ModelEdgesVisibilityParams, ModelEdgesVisibilityResponse>;
      };
      readonly lines: {
        readonly attribute: {
          readonly edge: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["lines"]["attribute"]["edge"]["attribute"] & TypedSchema<ModelLinesAttributeEdgeAttributeParams, ModelLinesAttributeEdgeAttributeResponse>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["lines"]["attribute"]["vertex"]["attribute"] & TypedSchema<ModelLinesAttributeVertexAttributeParams, ModelLinesAttributeVertexAttributeResponse>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["lines"]["visibility"] & TypedSchema<ModelLinesVisibilityParams, ModelLinesVisibilityResponse>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["model"]["lines"]["color"] & TypedSchema<ModelLinesColorParams, ModelLinesColorResponse>;
      };
      readonly points: {
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["points"]["visibility"] & TypedSchema<ModelPointsVisibilityParams, ModelPointsVisibilityResponse>;
        readonly size: (typeof json)["opengeodeweb_viewer"]["model"]["points"]["size"] & TypedSchema<ModelPointsSizeParams, ModelPointsSizeResponse>;
      };
      readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["visibility"] & TypedSchema<ModelVisibilityParams, ModelVisibilityResponse>;
      readonly register: (typeof json)["opengeodeweb_viewer"]["model"]["register"] & TypedSchema<ModelRegisterParams, ModelRegisterResponse>;
      readonly highlight: (typeof json)["opengeodeweb_viewer"]["model"]["highlight"] & TypedSchema<ModelHighlightParams, ModelHighlightResponse>;
      readonly get_blocks_bounds: (typeof json)["opengeodeweb_viewer"]["model"]["get_blocks_bounds"] & TypedSchema<ModelGetBlocksBoundsParams, ModelGetBlocksBoundsResponse>;
      readonly deregister: (typeof json)["opengeodeweb_viewer"]["model"]["deregister"] & TypedSchema<ModelDeregisterParams, ModelDeregisterResponse>;
      readonly surfaces: {
        readonly attribute: {
          readonly polygon: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["attribute"]["polygon"]["attribute"] & TypedSchema<ModelSurfacesAttributePolygonAttributeParams, ModelSurfacesAttributePolygonAttributeResponse>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["attribute"]["vertex"]["attribute"] & TypedSchema<ModelSurfacesAttributeVertexAttributeParams, ModelSurfacesAttributeVertexAttributeResponse>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["visibility"] & TypedSchema<ModelSurfacesVisibilityParams, ModelSurfacesVisibilityResponse>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["color"] & TypedSchema<ModelSurfacesColorParams, ModelSurfacesColorResponse>;
        readonly apply_textures: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["apply_textures"] & TypedSchema<ModelSurfacesApplyTexturesParams, ModelSurfacesApplyTexturesResponse>;
      };
    };
    readonly release_database: (typeof json)["opengeodeweb_viewer"]["release_database"] & TypedSchema<ReleaseDatabaseParams, ReleaseDatabaseResponse>;
    readonly kill: (typeof json)["opengeodeweb_viewer"]["kill"] & TypedSchema<KillParams, KillResponse>;
    readonly import_project: (typeof json)["opengeodeweb_viewer"]["import_project"] & TypedSchema<ImportProjectParams, ImportProjectResponse>;
    readonly viewer: {
      readonly update_data: (typeof json)["opengeodeweb_viewer"]["viewer"]["update_data"] & TypedSchema<ViewerUpdateDataParams, ViewerUpdateDataResponse>;
      readonly update_camera: (typeof json)["opengeodeweb_viewer"]["viewer"]["update_camera"] & TypedSchema<ViewerUpdateCameraParams, ViewerUpdateCameraResponse>;
      readonly threshold: (typeof json)["opengeodeweb_viewer"]["viewer"]["threshold"] & TypedSchema<ViewerThresholdParams, ViewerThresholdResponse>;
      readonly take_screenshot: (typeof json)["opengeodeweb_viewer"]["viewer"]["take_screenshot"] & TypedSchema<ViewerTakeScreenshotParams, ViewerTakeScreenshotResponse>;
      readonly slice: (typeof json)["opengeodeweb_viewer"]["viewer"]["slice"] & TypedSchema<ViewerSliceParams, ViewerSliceResponse>;
      readonly shrink: (typeof json)["opengeodeweb_viewer"]["viewer"]["shrink"] & TypedSchema<ViewerShrinkParams, ViewerShrinkResponse>;
      readonly set_z_scaling: (typeof json)["opengeodeweb_viewer"]["viewer"]["set_z_scaling"] & TypedSchema<ViewerSetZScalingParams, ViewerSetZScalingResponse>;
      readonly set_background_color: (typeof json)["opengeodeweb_viewer"]["viewer"]["set_background_color"] & TypedSchema<ViewerSetBackgroundColorParams, ViewerSetBackgroundColorResponse>;
      readonly ruler: (typeof json)["opengeodeweb_viewer"]["viewer"]["ruler"] & TypedSchema<ViewerRulerParams, ViewerRulerResponse>;
      readonly reset_visualization: (typeof json)["opengeodeweb_viewer"]["viewer"]["reset_visualization"] & TypedSchema<ViewerResetVisualizationParams, ViewerResetVisualizationResponse>;
      readonly reset_ruler: (typeof json)["opengeodeweb_viewer"]["viewer"]["reset_ruler"] & TypedSchema<ViewerResetRulerParams, ViewerResetRulerResponse>;
      readonly reset_camera: (typeof json)["opengeodeweb_viewer"]["viewer"]["reset_camera"] & TypedSchema<ViewerResetCameraParams, ViewerResetCameraResponse>;
      readonly render: (typeof json)["opengeodeweb_viewer"]["viewer"]["render"] & TypedSchema<ViewerRenderParams, ViewerRenderResponse>;
      readonly preview_points: (typeof json)["opengeodeweb_viewer"]["viewer"]["preview_points"] & TypedSchema<ViewerPreviewPointsParams, ViewerPreviewPointsResponse>;
      readonly picked_ids: (typeof json)["opengeodeweb_viewer"]["viewer"]["picked_ids"] & TypedSchema<ViewerPickedIDSParams, ViewerPickedIDSResponse>;
      readonly pick_colormap: (typeof json)["opengeodeweb_viewer"]["viewer"]["pick_colormap"] & TypedSchema<ViewerPickColormapParams, ViewerPickColormapResponse>;
      readonly highlight: (typeof json)["opengeodeweb_viewer"]["viewer"]["highlight"] & TypedSchema<ViewerHighlightParams, ViewerHighlightResponse>;
      readonly grid_scale: (typeof json)["opengeodeweb_viewer"]["viewer"]["grid_scale"] & TypedSchema<ViewerGridScaleParams, ViewerGridScaleResponse>;
      readonly get_point_position: (typeof json)["opengeodeweb_viewer"]["viewer"]["get_point_position"] & TypedSchema<ViewerGetPointPositionParams, ViewerGetPointPositionResponse>;
      readonly clipping_planes: (typeof json)["opengeodeweb_viewer"]["viewer"]["clipping_planes"] & TypedSchema<ViewerClippingPlanesParams, ViewerClippingPlanesResponse>;
      readonly axes: (typeof json)["opengeodeweb_viewer"]["viewer"]["axes"] & TypedSchema<ViewerAxesParams, ViewerAxesResponse>;
    };
  };
}

declare const schemas: Schemas;
export default schemas;
