// Generated by opengeodeweb-microservice-generate, do not edit.
import type json from "./opengeodeweb_viewer_schemas.json";

export interface GenericRegisterParams {
    id:   string;
    name: string;
}

export interface GenericDeregisterParams {
    id: string;
}

export interface MeshCellsAttributeCellAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshCellsAttributeCellAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshCellsAttributeCellAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshCellsAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshCellsAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshCellsAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshCellsVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshCellsColorParams {
    color: MeshCellsColorParamsColor;
    id:    string;
}

export interface MeshCellsColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshEdgesAttributeEdgeAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshEdgesAttributeEdgeAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshEdgesAttributeEdgeAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshEdgesAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshEdgesAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshEdgesAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshEdgesWidthParams {
    id:    string;
    width: number;
}

export interface MeshEdgesVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshEdgesColorParams {
    color: MeshEdgesColorParamsColor;
    id:    string;
}

export interface MeshEdgesColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPointsAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPointsAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPointsAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPointsVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshPointsSizeParams {
    id:   string;
    size: number;
}

export interface MeshPointsColorParams {
    color: MeshPointsColorParamsColor;
    id:    string;
}

export interface MeshPointsColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolygonsAttributePolygonAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPolygonsAttributePolygonAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPolygonsAttributePolygonAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolygonsAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPolygonsAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPolygonsAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolygonsVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshPolygonsColorParams {
    color: MeshPolygonsColorParamsColor;
    id:    string;
}

export interface MeshPolygonsColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolyhedraAttributePolyhedronAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPolyhedraAttributePolyhedronAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPolyhedraAttributePolyhedronAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolyhedraAttributeVertexAttributeParams {
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: MeshPolyhedraAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface MeshPolyhedraAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshPolyhedraVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshPolyhedraColorParams {
    color: MeshPolyhedraColorParamsColor;
    id:    string;
}

export interface MeshPolyhedraColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface MeshRegisterParams {
    id:   string;
    name: string;
}

export interface MeshHighlightParams {
    id:         string;
    visibility: boolean;
}

export interface MeshDeregisterParams {
    id: string;
}

export interface MeshColorParams {
    color: MeshColorParamsColor;
    id:    string;
}

export interface MeshColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface MeshApplyTexturesParams {
    id:       string;
    textures: MeshApplyTexturesParamsTexture[];
}

export interface MeshApplyTexturesParamsTexture {
    id:           string;
    texture_name: string;
}

export interface ModelBlocksAttributePolyhedronAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelBlocksAttributePolyhedronAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelBlocksAttributePolyhedronAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelBlocksAttributeVertexAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelBlocksAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelBlocksAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelBlocksVisibilityParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelBlocksColorParams {
    block_ids:      number[];
    collection_id?: string;
    color?:         ModelBlocksColorParamsColor;
    color_mode:     ColorMode;
    id:             string;
}

export interface ModelBlocksColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export enum ColorMode {
    Constant = "constant",
    Random = "random",
}

export interface ModelCornersAttributeVertexAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelCornersAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelCornersAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelCornersVisibilityParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelCornersColorParams {
    block_ids:      number[];
    collection_id?: string;
    color?:         ModelCornersColorParamsColor;
    color_mode:     ColorMode;
    id:             string;
}

export interface ModelCornersColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelEdgesVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface ModelLinesAttributeEdgeAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelLinesAttributeEdgeAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelLinesAttributeEdgeAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelLinesAttributeVertexAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelLinesAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelLinesAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelLinesVisibilityParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelLinesColorParams {
    block_ids:      number[];
    collection_id?: string;
    color?:         ModelLinesColorParamsColor;
    color_mode:     ColorMode;
    id:             string;
}

export interface ModelLinesColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelPointsVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface ModelPointsSizeParams {
    id:   string;
    size: number;
}

export interface ModelVisibilityParams {
    id:         string;
    visibility: boolean;
}

export interface ModelRegisterParams {
    id:   string;
    name: string;
}

export interface ModelHighlightParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelGetBlocksBoundsParams {
    block_ids: number[];
    id:        string;
}

export interface ModelDeregisterParams {
    id: string;
}

export interface ModelSurfacesAttributePolygonAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelSurfacesAttributePolygonAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelSurfacesAttributePolygonAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelSurfacesAttributeVertexAttributeParams {
    block_ids:      number[];
    id:             string;
    item:           number;
    maximum:        number;
    minimum:        number;
    name:           string;
    no_data_color?: ModelSurfacesAttributeVertexAttributeParamsNoDataColor;
    /**
     * Flat array of [value, r, g, b, ...]
     */
    points: number[];
}

export interface ModelSurfacesAttributeVertexAttributeParamsNoDataColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelSurfacesVisibilityParams {
    block_ids:  number[];
    id:         string;
    visibility: boolean;
}

export interface ModelSurfacesColorParams {
    block_ids:      number[];
    collection_id?: string;
    color?:         ModelSurfacesColorParamsColor;
    color_mode:     ColorMode;
    id:             string;
}

export interface ModelSurfacesColorParamsColor {
    alpha: number;
    blue:  number;
    green: number;
    red:   number;
}

export interface ModelSurfacesApplyTexturesParams {
    id:       string;
    textures: ModelSurfacesApplyTexturesParamsTexture[];
}

export interface ModelSurfacesApplyTexturesParamsTexture {
    texture_file_name: string;
    texture_name:      string;
}

export interface KillParams {
}

export interface ImportProjectParams {
}

export interface ViewerUpdateDataParams {
    id: string;
}

export interface ViewerUpdateCameraParams {
    camera_options: CameraOptions;
    [property: string]: any;
}

export interface CameraOptions {
    clipping_range: number[];
    focal_point:    number[];
    position:       number[];
    view_angle:     number;
    view_up:        number[];
    [property: string]: any;
}

export interface ViewerThresholdParams {
    attribute?: Attribute;
    ids:        string[];
}

export interface Attribute {
    item:     number;
    location: Location;
    maximum:  number;
    minimum:  number;
    name:     string;
}

export enum Location {
    Cell = "cell",
    Point = "point",
}

export interface ViewerTakeScreenshotParams {
    filename:           string;
    include_background: boolean;
    output_extension:   OutputExtension;
}

export enum OutputExtension {
    Jpg = "jpg",
    PNG = "png",
}

export interface ViewerSliceParams {
    ids:    string[];
    slices: Slice[];
}

export interface Slice {
    axis:  number;
    index: number;
}

export interface ViewerShrinkParams {
    ids:           string[];
    shrink_factor: number;
}

export interface ViewerSetZScalingParams {
    z_scale: number;
}

export interface ViewerSetBackgroundColorParams {
    color: ViewerSetBackgroundColorParamsColor;
}

export interface ViewerSetBackgroundColorParamsColor {
    b: number;
    g: number;
    r: number;
}

export interface ViewerRulerParams {
    points: Array<number[]>;
}

export interface ViewerResetVisualizationParams {
}

export interface ViewerResetRulerParams {
}

export interface ViewerResetCameraParams {
}

export interface ViewerRenderParams {
}

export interface ViewerPreviewPointsParams {
    closed?: boolean;
    points:  Point[];
    style:   Style;
}

export interface Point {
    x: number;
    y: number;
    z: number;
}

export enum Style {
    Curve = "curve",
    Points = "points",
    Surface = "surface",
}

export interface ViewerPickedIDSParams {
    ids: string[];
    x:   number;
    y:   number;
}

export interface ViewerPickColormapParams {
    x: number;
    y: number;
    [property: string]: any;
}

export interface ViewerHighlightParams {
    field_type: FieldType;
    ids:        string[];
    x:          number;
    y:          number;
}

export enum FieldType {
    Cell = "CELL",
    Point = "POINT",
}

export interface ViewerGridScaleParams {
    visibility: boolean;
}

export interface ViewerGetPointPositionParams {
    x: number;
    y: number;
}

export interface ViewerClippingPlanesParams {
    ids:    string[];
    planes: Plane[];
}

export interface Plane {
    normal: number[];
    origin: number[];
}

export interface ViewerAxesParams {
    visibility: boolean;
}

export interface ErrorResponse {
    code:        number;
    description: string;
    name:        string;
}

// `__params` and `__response` only exist at type level, to infer request/response types from a schema.
// A type alias (not an interface) keeps the implicit index signature of the JSON type it is intersected with.
export type TypedSchema<Params, Response> = {
  readonly __params?: Params;
  readonly __response?: Response;
};

export interface Schemas {
  readonly opengeodeweb_viewer: {
    readonly generic: {
      readonly register: (typeof json)["opengeodeweb_viewer"]["generic"]["register"] & TypedSchema<GenericRegisterParams, unknown>;
      readonly deregister: (typeof json)["opengeodeweb_viewer"]["generic"]["deregister"] & TypedSchema<GenericDeregisterParams, unknown>;
    };
    readonly mesh: {
      readonly cells: {
        readonly attribute: {
          readonly cell: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["cells"]["attribute"]["cell"]["attribute"] & TypedSchema<MeshCellsAttributeCellAttributeParams, unknown>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["cells"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshCellsAttributeVertexAttributeParams, unknown>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["cells"]["visibility"] & TypedSchema<MeshCellsVisibilityParams, unknown>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["cells"]["color"] & TypedSchema<MeshCellsColorParams, unknown>;
      };
      readonly edges: {
        readonly attribute: {
          readonly edge: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["attribute"]["edge"]["attribute"] & TypedSchema<MeshEdgesAttributeEdgeAttributeParams, unknown>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshEdgesAttributeVertexAttributeParams, unknown>;
          };
        };
        readonly width: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["width"] & TypedSchema<MeshEdgesWidthParams, unknown>;
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["visibility"] & TypedSchema<MeshEdgesVisibilityParams, unknown>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["edges"]["color"] & TypedSchema<MeshEdgesColorParams, unknown>;
      };
      readonly points: {
        readonly attribute: {
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["points"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshPointsAttributeVertexAttributeParams, unknown>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["points"]["visibility"] & TypedSchema<MeshPointsVisibilityParams, unknown>;
        readonly size: (typeof json)["opengeodeweb_viewer"]["mesh"]["points"]["size"] & TypedSchema<MeshPointsSizeParams, unknown>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["points"]["color"] & TypedSchema<MeshPointsColorParams, unknown>;
      };
      readonly polygons: {
        readonly attribute: {
          readonly polygon: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["polygons"]["attribute"]["polygon"]["attribute"] & TypedSchema<MeshPolygonsAttributePolygonAttributeParams, unknown>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["polygons"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshPolygonsAttributeVertexAttributeParams, unknown>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["polygons"]["visibility"] & TypedSchema<MeshPolygonsVisibilityParams, unknown>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["polygons"]["color"] & TypedSchema<MeshPolygonsColorParams, unknown>;
      };
      readonly polyhedra: {
        readonly attribute: {
          readonly polyhedron: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["polyhedra"]["attribute"]["polyhedron"]["attribute"] & TypedSchema<MeshPolyhedraAttributePolyhedronAttributeParams, unknown>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["mesh"]["polyhedra"]["attribute"]["vertex"]["attribute"] & TypedSchema<MeshPolyhedraAttributeVertexAttributeParams, unknown>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["polyhedra"]["visibility"] & TypedSchema<MeshPolyhedraVisibilityParams, unknown>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["polyhedra"]["color"] & TypedSchema<MeshPolyhedraColorParams, unknown>;
      };
      readonly visibility: (typeof json)["opengeodeweb_viewer"]["mesh"]["visibility"] & TypedSchema<MeshVisibilityParams, unknown>;
      readonly register: (typeof json)["opengeodeweb_viewer"]["mesh"]["register"] & TypedSchema<MeshRegisterParams, unknown>;
      readonly highlight: (typeof json)["opengeodeweb_viewer"]["mesh"]["highlight"] & TypedSchema<MeshHighlightParams, unknown>;
      readonly deregister: (typeof json)["opengeodeweb_viewer"]["mesh"]["deregister"] & TypedSchema<MeshDeregisterParams, unknown>;
      readonly color: (typeof json)["opengeodeweb_viewer"]["mesh"]["color"] & TypedSchema<MeshColorParams, unknown>;
      readonly apply_textures: (typeof json)["opengeodeweb_viewer"]["mesh"]["apply_textures"] & TypedSchema<MeshApplyTexturesParams, unknown>;
    };
    readonly model: {
      readonly blocks: {
        readonly attribute: {
          readonly polyhedron: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["blocks"]["attribute"]["polyhedron"]["attribute"] & TypedSchema<ModelBlocksAttributePolyhedronAttributeParams, unknown>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["blocks"]["attribute"]["vertex"]["attribute"] & TypedSchema<ModelBlocksAttributeVertexAttributeParams, unknown>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["blocks"]["visibility"] & TypedSchema<ModelBlocksVisibilityParams, unknown>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["model"]["blocks"]["color"] & TypedSchema<ModelBlocksColorParams, unknown>;
      };
      readonly corners: {
        readonly attribute: {
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["corners"]["attribute"]["vertex"]["attribute"] & TypedSchema<ModelCornersAttributeVertexAttributeParams, unknown>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["corners"]["visibility"] & TypedSchema<ModelCornersVisibilityParams, unknown>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["model"]["corners"]["color"] & TypedSchema<ModelCornersColorParams, unknown>;
      };
      readonly edges: {
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["edges"]["visibility"] & TypedSchema<ModelEdgesVisibilityParams, unknown>;
      };
      readonly lines: {
        readonly attribute: {
          readonly edge: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["lines"]["attribute"]["edge"]["attribute"] & TypedSchema<ModelLinesAttributeEdgeAttributeParams, unknown>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["lines"]["attribute"]["vertex"]["attribute"] & TypedSchema<ModelLinesAttributeVertexAttributeParams, unknown>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["lines"]["visibility"] & TypedSchema<ModelLinesVisibilityParams, unknown>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["model"]["lines"]["color"] & TypedSchema<ModelLinesColorParams, unknown>;
      };
      readonly points: {
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["points"]["visibility"] & TypedSchema<ModelPointsVisibilityParams, unknown>;
        readonly size: (typeof json)["opengeodeweb_viewer"]["model"]["points"]["size"] & TypedSchema<ModelPointsSizeParams, unknown>;
      };
      readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["visibility"] & TypedSchema<ModelVisibilityParams, unknown>;
      readonly register: (typeof json)["opengeodeweb_viewer"]["model"]["register"] & TypedSchema<ModelRegisterParams, unknown>;
      readonly highlight: (typeof json)["opengeodeweb_viewer"]["model"]["highlight"] & TypedSchema<ModelHighlightParams, unknown>;
      readonly get_blocks_bounds: (typeof json)["opengeodeweb_viewer"]["model"]["get_blocks_bounds"] & TypedSchema<ModelGetBlocksBoundsParams, unknown>;
      readonly deregister: (typeof json)["opengeodeweb_viewer"]["model"]["deregister"] & TypedSchema<ModelDeregisterParams, unknown>;
      readonly surfaces: {
        readonly attribute: {
          readonly polygon: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["attribute"]["polygon"]["attribute"] & TypedSchema<ModelSurfacesAttributePolygonAttributeParams, unknown>;
          };
          readonly vertex: {
            readonly attribute: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["attribute"]["vertex"]["attribute"] & TypedSchema<ModelSurfacesAttributeVertexAttributeParams, unknown>;
          };
        };
        readonly visibility: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["visibility"] & TypedSchema<ModelSurfacesVisibilityParams, unknown>;
        readonly color: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["color"] & TypedSchema<ModelSurfacesColorParams, unknown>;
        readonly apply_textures: (typeof json)["opengeodeweb_viewer"]["model"]["surfaces"]["apply_textures"] & TypedSchema<ModelSurfacesApplyTexturesParams, unknown>;
      };
    };
    readonly kill: (typeof json)["opengeodeweb_viewer"]["kill"] & TypedSchema<KillParams, unknown>;
    readonly import_project: (typeof json)["opengeodeweb_viewer"]["import_project"] & TypedSchema<ImportProjectParams, unknown>;
    readonly viewer: {
      readonly update_data: (typeof json)["opengeodeweb_viewer"]["viewer"]["update_data"] & TypedSchema<ViewerUpdateDataParams, unknown>;
      readonly update_camera: (typeof json)["opengeodeweb_viewer"]["viewer"]["update_camera"] & TypedSchema<ViewerUpdateCameraParams, unknown>;
      readonly threshold: (typeof json)["opengeodeweb_viewer"]["viewer"]["threshold"] & TypedSchema<ViewerThresholdParams, unknown>;
      readonly take_screenshot: (typeof json)["opengeodeweb_viewer"]["viewer"]["take_screenshot"] & TypedSchema<ViewerTakeScreenshotParams, unknown>;
      readonly slice: (typeof json)["opengeodeweb_viewer"]["viewer"]["slice"] & TypedSchema<ViewerSliceParams, unknown>;
      readonly shrink: (typeof json)["opengeodeweb_viewer"]["viewer"]["shrink"] & TypedSchema<ViewerShrinkParams, unknown>;
      readonly set_z_scaling: (typeof json)["opengeodeweb_viewer"]["viewer"]["set_z_scaling"] & TypedSchema<ViewerSetZScalingParams, unknown>;
      readonly set_background_color: (typeof json)["opengeodeweb_viewer"]["viewer"]["set_background_color"] & TypedSchema<ViewerSetBackgroundColorParams, unknown>;
      readonly ruler: (typeof json)["opengeodeweb_viewer"]["viewer"]["ruler"] & TypedSchema<ViewerRulerParams, unknown>;
      readonly reset_visualization: (typeof json)["opengeodeweb_viewer"]["viewer"]["reset_visualization"] & TypedSchema<ViewerResetVisualizationParams, unknown>;
      readonly reset_ruler: (typeof json)["opengeodeweb_viewer"]["viewer"]["reset_ruler"] & TypedSchema<ViewerResetRulerParams, unknown>;
      readonly reset_camera: (typeof json)["opengeodeweb_viewer"]["viewer"]["reset_camera"] & TypedSchema<ViewerResetCameraParams, unknown>;
      readonly render: (typeof json)["opengeodeweb_viewer"]["viewer"]["render"] & TypedSchema<ViewerRenderParams, unknown>;
      readonly preview_points: (typeof json)["opengeodeweb_viewer"]["viewer"]["preview_points"] & TypedSchema<ViewerPreviewPointsParams, unknown>;
      readonly picked_ids: (typeof json)["opengeodeweb_viewer"]["viewer"]["picked_ids"] & TypedSchema<ViewerPickedIDSParams, unknown>;
      readonly pick_colormap: (typeof json)["opengeodeweb_viewer"]["viewer"]["pick_colormap"] & TypedSchema<ViewerPickColormapParams, unknown>;
      readonly highlight: (typeof json)["opengeodeweb_viewer"]["viewer"]["highlight"] & TypedSchema<ViewerHighlightParams, unknown>;
      readonly grid_scale: (typeof json)["opengeodeweb_viewer"]["viewer"]["grid_scale"] & TypedSchema<ViewerGridScaleParams, unknown>;
      readonly get_point_position: (typeof json)["opengeodeweb_viewer"]["viewer"]["get_point_position"] & TypedSchema<ViewerGetPointPositionParams, unknown>;
      readonly clipping_planes: (typeof json)["opengeodeweb_viewer"]["viewer"]["clipping_planes"] & TypedSchema<ViewerClippingPlanesParams, unknown>;
      readonly axes: (typeof json)["opengeodeweb_viewer"]["viewer"]["axes"] & TypedSchema<ViewerAxesParams, unknown>;
    };
  };
}

declare const schemas: Schemas;
export default schemas;
