name: Test

on:
  push:
    branches-ignore:
      - master
      - next

jobs:
  test:
    uses: Geode-solutions/actions/.github/workflows/py-test.yml@master
    with:
      repos: ${{ vars.REPOS }}
      node: true
    secrets: inherit
